 spring.application.name=backend

spring.datasource.url=jdbc:postgresql://ep-long-darkness-axchxm8a-pooler.c-4.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_ImSOCk8TJRV4&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ImSOCk8TJRV4

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=senati
