spring.application.name=Veterinaria_xime

# Configuración de conexión a Neon DB
spring.datasource.url=jdbc:postgresql://ep-restless-thunder-aej0zbou-pooler.c-2.us-east-2.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_C4SzoBDgFAU8

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Apuntamos al esquema predeterminado de PostgreSQL
spring.jpa.properties.hibernate.default_schema=public