spring.application.name=Veterinaria_xime

# Configuración con Variables de Entorno y valores de respaldo (fallback)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Esquema predeterminado
spring.jpa.properties.hibernate.default_schema=public