spring.application.name=ServicioCancha

# Configuración del Puerto
server.port=8080

# Conexión a la base de datos Neon (PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-quiet-boat-ax18fqry.c-4.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_rOznAdwNgh49
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
