spring.application.name=VoleyPlay

<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://ep-orange-sky-b4k1h0gz-pooler.c-6.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
=======
spring.datasource.url=jdbc:postgresql://ep-quiet-snow-axmryqji-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ZmcHSqIfk13D
>>>>>>> 4936a8e41354881b4c7e87e6cc7f3b8d3f1239b9

spring.datasource.driver-class-name=org.postgresql.Driver
<<<<<<< HEAD
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
=======
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

>>>>>>> b27d57926b6f0efd12eb91207e8a0dcaaa505b32
